### ISSUE TITLE
 Cannot read property 'pid' of null                   

### ISSUE THREAD

**Issue by kgdev** [narirou/gulp-develop-server#14] opened 2015-04-29 13:04 UTC
·
/home/ubuntu/weidian/backend/node_modules/gulp-develop-server/index.js:188                                                                                                                    │············
                        var pid = gutil.colors.magenta( app.child.pid );                                                                                                                      │············
                                                                 ^                                                                                                                            │············
TypeError: Cannot read property 'pid' of null                                                                                                                                                 │············
    at ChildProcess.stopped (/home/ubuntu/weidian/backend/node_modules/gulp-develop-server/index.js:188:45)                                                                                   │············
    at ChildProcess.g (events.js:199:16)                                                                                                                                                      │············
    at ChildProcess.emit (events.js:129:20)                                                                                                                                                   │············
    at maybeClose (child_process.js:1015:16)                                                                                                                                                  │············
    at Socket.<anonymous> (child_process.js:1183:11)                                                                                                                                          │············
    at Socket.emit (events.js:107:17)                                                                                                                                                         │············
    at Pipe.close (net.js:485:12)

**Comment by kgdev** [comment] 2015-05-03 15:44
var pid = gutil.colors.magenta( app.child.pid );

TypeError: Cannot read property 'pid' of null

**Comment by nforysinski** [comment] 2015-05-05 16:39
This issue is most persistent when watching the many results of a js/css set of gulp tasks. For instance, I have several js and css files that need to be minified and linted, which then get moved to a "dist" folder. My develop task is as follows:

```
gulp.task('watch', ['server:start'], function () {

    var notify = function(file) {
        server.changed( function( error ) {
            if( ! error ) lr.changed( file.path );
        });
    };

    gulp.watch(paths.css, ['sass']);
    gulp.watch(paths.html, ['compresshtml']);
    gulp.watch(paths.js, ['lint', 'compressjs']);
    gulp.watch(['./public/dist/**/*']).on('change', notify);
});
```

This yields the child pid error as well as several other event errors.

**Comment by chimerast** [comment] 2015-05-09 06:58
I think this issue is caused by a bug of checking multiple restarts. 

https://github.com/narirou/gulp-develop-server/blob/master/index.js#L206-L210
```js
	// already called this function
	if( isChanged ) {
		isChanged = false; // *** I think this line cause the problem. It is unnecessary code. ***
		return done( null, 'Development server already received restart requests.', callback );
	}
```

It calls the `kill` function multiple times when the watcher task calls `restart` multiple times in a very short time.

**Comment by narirou** [comment] 2015-05-09 21:24
@kgdev, @nforysinski, @chimerast
Thank you for the detailed report. 

As it is said, the value of isChanged was incorrect.
But, as a result, I do not know whether this issue has been fixed.
I plan to verify the reproducibility of this issue, and add more test code.

**Comment by narirou** [comment] 2015-11-01 15:56
I think this error fixed by previous commit. (thanks @chimerast)
If not, please reopen this issue. Thanks.

**Closed by narirou** 2015-11-01 15:56 UTC
